require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

#Layout/LineLength:
#  AllowedPatterns: ['(\A|\s)#']
#
#Metrics/BlockLength:
#  Exclude:
#    - 'spec/**/*'
#
#Lint/AmbiguousBlockAssociation:
#  Exclude:
#    - 'spec/**/*'